require("dotenv").config();
const { Client, GatewayIntentBits, EmbedBuilder } = require("discord.js");
const mongoose = require("mongoose");
const http = require("http");

const ChatLog = require("./models/ChatLog");
const { checkAndModerateProfanity } = require("./services/autoModService");
const {
  generateChatSummary,
  answerContextualQuery,
} = require("./services/aiService");

// Process-level guards
process.on("unhandledRejection", (reason) =>
  console.error("Unhandled Rejection:", reason),
);
process.on("uncaughtException", (error) =>
  console.error("Uncaught Exception:", error),
);

const client = new Client({
  intents: [
    GatewayIntentBits.Guilds,
    GatewayIntentBits.GuildMessages,
    GatewayIntentBits.MessageContent,
  ],
});

client.once("clientReady", () => {
  console.log(`[ATX AI] Bot online as ${client.user.tag}`);
});

client.on("messageCreate", async (message) => {
  // Ignore bots and DM channels
  if (message.author.bot || !message.guild) return;

  // 1. Auto-Moderation Filter (deletes message if profanity detected)
  const wasViolated = await checkAndModerateProfanity(message);
  if (wasViolated) return;

  // 2. Persist Message into Rolling Memory (MongoDB)
  ChatLog.create({
    guildId: message.guild.id,
    channelId: message.channel.id,
    authorId: message.author.id,
    authorTag: message.author.username,
    content: message.content,
  }).catch(() => {});

  // 3. Check for AI Trigger (?atx <query> or @Bot mention)
  const isTagged = message.mentions.has(client.user);
  const isPrefixed = message.content.toLowerCase().startsWith("?atx");

  if (isTagged || isPrefixed) {
    let cleanPrompt = message.content;
    if (isPrefixed) {
      cleanPrompt = cleanPrompt.slice(4).trim();
    } else {
      cleanPrompt = cleanPrompt
        .replace(new RegExp(`<@!?${client.user.id}>`), "")
        .trim();
    }

    if (!cleanPrompt) {
      return message.reply(
        "How can I assist you? Ask me any question or type `?atx summary` for a channel recap.",
      );
    }

    await message.channel.sendTyping();

    // Route: Summary Request
    if (/summary|what happened|recap|tl;?dr/i.test(cleanPrompt)) {
      try {
        const summary = await generateChatSummary(message.channel, 3);

        const summaryEmbed = new EmbedBuilder()
          .setColor(0x5865f2)
          .setAuthor({
            name: "CHANNEL TIMELINE SUMMARY • LAST 3 HOURS",
            iconURL: message.guild.iconURL() || undefined,
          })
          .setDescription(summary)
          .setFooter({ text: "Generated by ATX AI Engine" })
          .setTimestamp();

        return message.reply({ embeds: [summaryEmbed] });
      } catch (err) {
        console.error("Summary error:", err);
        return message.reply("Failed to generate summary at this moment.");
      }
    }

    // Route: Contextual Question Answering
    try {
      const response = await answerContextualQuery(message, cleanPrompt);

      const aiEmbed = new EmbedBuilder()
        .setColor(0x00f5d4)
        .setAuthor({
          name: "ATX INTELLIGENCE SYSTEM",
          iconURL: client.user.displayAvatarURL(),
        })
        .setDescription(response)
        .setFooter({ text: `Requested by @${message.author.username}` });

      return message.reply({ embeds: [aiEmbed] });
    } catch (err) {
      console.error("AI Generation error:", err);
      return message.reply(
        "My neural engine ran into a snag. Please ask again shortly.",
      );
    }
  }
});

// Database Connection & Login
mongoose
  .connect(process.env.MONGO_URI)
  .then(() => {
    console.log("[Database] Connected to MongoDB Atlas.");
    client.login(process.env.DISCORD_TOKEN);
  })
  .catch((err) => console.error("Database Connection Failure:", err));

// Uptime Ping Server
const PORT = process.env.PORT || 3000;
http
  .createServer((req, res) => {
    res.writeHead(200, { "Content-Type": "text/plain" });
    res.end("ATX AI Moderator is active.");
  })
  .listen(PORT, () =>
    console.log(`[Web] Keep-alive server running on port ${PORT}`),
  );
